---
engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  coffeelint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
  eslint:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
  - useradmin/app/**
  - useradmin/lib/**
  - "**.slim"
  - "**.rb"
  - "**.rake"
  - "**.css"
  - "**.scss"
  - "**.js"
exclude_paths:
- useradmin/config/**/*
- useradmin/db/**/*
- useradmin/script/**/*
- useradmin/spec/**/*
- useradmin/vendor/**/*
