- name: create database user
  postgresql_user: user={{ item.db_user }} password={{ item.db_password | vault }} role_attr_flags={{ item.db_user_roles }}
  become_user: postgres
  with_items:
    - "{{ postgres.databases }}"
  tags: postgres

- name: create database
  postgresql_db: name={{ item.db_name }}
                 owner={{ item.db_user }}
                 encoding='UTF-8'
                 lc_collate='en_US.UTF-8'
                 lc_ctype='en_US.UTF-8'
                 template='template0'
  become_user: postgres
  with_items:
    - "{{ postgres.databases }}"
  tags: postgres
