default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: 127.0.0.1
  database: useradmin_development
  username: useradmin
  password: useradmin

test:
  <<: *default
  database: useradmin_test

acceptance:
  <<: *default
  host: 127.0.0.1
  database: useradmin_acceptance
  username: useradmin
  password: <%= `cat /etc/useradmin/db_password 2>/dev/null` %>

production:
  <<: *default
  database: useradmin_production
  username: useradmin
  password: <%= `cat /etc/useradmin/db_password 2>/dev/null` %>
