default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  host: 127.0.0.1
  database: useradmin_development
  username: useradmin
  password: useradmin

test:
  <<: *default
  database: useradmin_test

acceptance:
  <<: *default
  host: 127.0.0.1
  database: useradmin_acceptance
  username: useradmin
  password: useradmin

production:
  <<: *default
  database: useradmin_production
  username: useradmin
  password: <%= ENV['USERADMIN_DATABASE_PASSWORD'] %>
