---
- hosts: useradmin
  become: yes
  roles:
    - { role: 'copy_config_files', when: env == 'development', tags: 'copy_config_files' }
    - common
    - git
    - postgres
    - ruby
    - apache
    - passenger
    - shibboleth
    - { role: 'java', when: env == 'development' }
    - { role: 'mujina' } # , when: env == 'development'
    - useradmin
