- name: Enable remote authentication
  lineinfile:
    dest: /etc/one/sunstone-server.conf
    regexp: "^:auth:"
    line: ":auth: remote"
  register: enable_remote_auth
  notify: restart apache
  tags:
    - one

- name: Fix REMOTE_USER header
  lineinfile:
    dest: /usr/lib/one/ruby/cloud/CloudAuth/RemoteCloudAuth.rb
    regexp: "env\\['(HTTP_)?REMOTE_USER'\\]"
    line: "        remote_user   = env['HTTP_REMOTE_USER']"
  notify: restart apache
  tags:
    - one

- name: Restart opennebula/apache
  service: name={{ item }} state=restarted
  when: env in ['development', 'acceptance'] and enable_remote_auth.changed
  with_items:
    - opennebula
    - apache2
  tags:
    - one

- name: Create OpenNebula development test users
  shell: oneuser create {{item}} {{item}} --driver public
  with_items:
    - admin
    - user
  when: env == 'development'
  register: create_users
  failed_when: "'UserAllocate' in create_users.stderr and 'NAME is already taken by USER' not in create_users.stderr"
  changed_when: "create_users.rc == 0"
  tags:
    - one

- name: Create OpenNebula acceptance test users
  shell: oneuser create {{item}} {{item}} --driver public
  with_items:
    - isaac
    - jweeler
    - student21
    - teacher10
  when: env == 'acceptance'
  register: create_users
  failed_when: "'UserAllocate' in create_users.stderr and 'NAME is already taken by USER' not in create_users.stderr"
  changed_when: "create_users.rc == 0"
  tags:
    - one

- name: Put development admin in oneadmin group
  shell: oneuser chgrp admin oneadmin
  when: env == 'development' and create_users.changed
  tags:
    - one

- name: Put acceptance admin in oneadmin group
  shell: oneuser chgrp isaac oneadmin
  when: env == 'acceptance' and create_users.changed
  tags:
    - one

- name: Create OpenNebula API user
  shell: oneuser create useradmin useradmin
  when: env in ['development', 'acceptance']
  register: command_result
  failed_when: "'UserAllocate' in command_result.stderr and 'NAME is already taken by USER' not in command_result.stderr"
  changed_when: "command_result.rc == 0"
  tags:
    - one
