- name: Enable remote authentication
  lineinfile:
    dest: /etc/one/sunstone-server.conf
    regexp: "^:auth:"
    line: ":auth: remote"
  register: enable_remote_auth
  notify: restart apache
  tags:
    - one

- name: Restart opennebula/apache
  service: name={{ item }} state=restarted
  when: env in ['development', 'acceptance'] and enable_remote_auth.changed
  with_items:
    - opennebula
    - apache2
  tags:
    - one

- name: Show password column in admin view
  lineinfile:
    dest: /etc/one/sunstone-views/admin.yaml
    regexp: "- 5         # Password"
    line: "            - 5         # Password"
  notify: restart apache
  tags:
    - one

- name: Disable User.update_password
  lineinfile:
      dest: /etc/one/sunstone-views/{{ item }}.yaml
      regexp: "User.update_password:"
      line: "            User.update_password: false"
  with_items:
    - admin
    - admin_vcenter
    - cloud
    - cloud_vcenter
    - groupadmin
    - groupadmin_vcenter
    - user
  notify: restart apache
  tags:
    - one

- name: Disable Settings.change_password
  lineinfile:
      dest: /etc/one/sunstone-views/{{ item }}.yaml
      regexp: "Settings.change_password:"
      line: "            Settings.change_password: false"
  with_items:
    - admin
    - admin_vcenter
    - cloud
    - cloud_vcenter
    - groupadmin
    - groupadmin_vcenter
    - user
  notify: restart apache
  tags:
    - one