- name: Fix REMOTE_USER header
  lineinfile:
    dest: /usr/lib/one/ruby/cloud/CloudAuth/RemoteCloudAuth.rb
    regexp: "env\\['(HTTP_)?REMOTE_USER'\\]"
    line: "        remote_user   = env['HTTP_REMOTE_USER']"
  notify: restart apache
  tags:
    - one

- name: Copy custom login file
  copy:
    src: _login_x509_custom.erb
    dest: /usr/lib/one/sunstone/views/_login_x509_custom.erb
    owner: oneadmin
    group: oneadmin
    mode: 0644
  notify: restart apache
  tags:
    - one

- name: Show custom login file
  lineinfile:
    dest: /usr/lib/one/sunstone/views/login.erb
    regexp: "<%= erb :_login_x509"
    line: '<%= erb :_login_x509_custom %>'
  notify: restart apache
  tags:
    - one

- name: Hide Sign Out button
  lineinfile:
    dest: /usr/lib/one/sunstone/views/index.erb
    line: "    <style>.is-submenu-item.is-dropdown-submenu-item .logout { display: none; }</style>"
    insertbefore: "</head>"
  notify: restart apache
  tags:
    - one
