- name: Ensure apache2 ssl directory exists
  file: path=/etc/apache2/ssl state=directory mode=0755
  when: env == 'development'
  tags: apache

- name: Copy certificates
  copy: src=development-certificates/{{ item }} dest=/etc/apache2/ssl/{{ item }}
  with_items:
    - cert.pem
    - key.pem
  notify:
    - restart apache
  when: env == 'development'
  tags: apache


- name: Create useradmin vhost
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/useradmin.conf
  notify: restart apache
  tags:
    - apache

- name: Enable useradmin vhost
  file: src=/etc/apache2/sites-available/useradmin.conf dest=/etc/apache2/sites-enabled/useradmin.conf state=link
  notify: restart apache
  tags:
    - apache
