- name: Ensure apache2 ssl directory exists
  file: path=/etc/apache2/ssl state=directory mode=0755
  tags: apache

- name: Copy development certificates
  copy: src=development-certificates/{{ item }} dest=/etc/apache2/ssl/{{ item }}
  with_items:
    - cert.pem
    - key.pem
  notify:
    - restart apache
  when: env == 'development'
  tags: apache


- name: Create useradmin vhost
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/useradmin.conf
  notify: restart apache
  tags:
    - apache

- name: Enable useradmin vhost
  shell: a2ensite useradmin
  notify: restart apache
  tags:
    - apache
