- name: Create useradmin vhost
  template: src=vhost.conf.j2 dest=/etc/apache2/sites-available/useradmin.conf
  notify: restart apache
  tags:
    - apache

- name: Enable useradmin vhost
  file: src=/etc/apache2/sites-available/useradmin.conf dest=/etc/apache2/sites-enabled/useradmin.conf state=link
  notify: restart apache
  tags:
    - apache
