- name: Install development dependencies
  apt: pkg={{ item }} state=latest
  with_items:
    - qt5-default
    - libqt5webkit5-dev
    - gstreamer1.0-plugins-base
    - gstreamer1.0-tools
    - gstreamer1.0-x
  when: env == 'development'
  tags: useradmin

- { include: mailcatcher.yml, when: env == 'development' or env == 'acceptance' }
- { include: letsencrypt.yml, when: env == 'acceptance' }
- include: apache.yml
- include: passenger.yml
- include: shibboleth.yml
