env: development
virtual_host: 192.168.111.171

surfconext:
  idp:
    sso_entity_id: http://mock-idp
    sso_url: http://192.168.111.171:8080/idp/SingleSignOnService

postgres:
  version: "9.4"
  database:
    host: 127.0.0.1/32
    name: useradmin_development
    user: useradmin
    password: useradmin
    user_roles: "LOGIN,CREATEDB"

one:
  sunstone_url: http://192.168.111.170
  xml_rpc_url: http://192.168.111.170:2633


ssl:
  cert: /etc/apache2/ssl/cert.pem
  key: /etc/apache2/ssl/key.pem