env: acceptance
virtual_host: useradmin.cloudconext-sara.surf-hosted.nl

surfconext:
  idp:
    sso_url: http://{{ virtual_host }}:8080/idp/SingleSignOnService

postgres:
  version: "9.4"
  database:
    host: 127.0.0.1/32
    name: useradmin_acceptance
    user: useradmin
    password: useradmin
    user_roles: "LOGIN,CREATEDB"

one_url: http://10.100.155.4
