---

env: development
virtual_hostname: 192.168.111.171

postgres:
  version: "9.4"
  database:
    host: 127.0.0.1/32
    name: useradmin_development
    user: useradmin
    password: useradmin
    user_roles: "LOGIN,CREATEDB"

admins:
  - bforma
  - svdiepen

ruby:
  gem_home: /home/surfsara/.gem

passenger:
  max_pool_size: 10
  max_instances_per_app: 5
  friendly_error_pages: "on"
