env: acceptance

virtual_host: useradmin.cloudconext-sara.surf-hosted.nl

surfconext:
  idp:
    sso_entity_id: https://engine.surfconext.nl/authentication/idp/metadata
    sso_url: http://{{ virtual_host }}:8080/idp/SingleSignOnService

postgres:
  version: "9.4"
  database:
    host: 127.0.0.1/32
    name: useradmin_acceptance
    user: useradmin
    password: useradmin
    user_roles: "LOGIN,CREATEDB"

one_url: http://10.100.155.4

# Ansistrano
ansistrano_deploy_from: "{{ playbook_dir }}/../useradmin/" # Where my local project is (relative or absolute path)
ansistrano_deploy_to: "/var/www/useradmin/" # Base path to deploy to.
ansistrano_version_dir: "releases" # Releases folder name
ansistrano_current_dir: "current" # Softlink name. You should rarely changed it.
ansistrano_current_via: "symlink" # Deployment strategy who code should be deployed to current path. Options are symlink or rsync
ansistrano_shared_paths: ['tmp', 'log'] # Shared paths to symlink to release dir
ansistrano_shared_files: [] # Shared files to symlink to release dir
ansistrano_keep_releases: 5 # Releases to keep after a new deployment. See "Pruning old releases".
ansistrano_deploy_via: "rsync" # Method used to deliver the code to the server. Options are copy, rsync, git, s3 or download.
ansistrano_allow_anonymous_stats: no

# Variables used in the rsync deployment strategy
ansistrano_rsync_extra_params: "" # Extra parameters to use when deploying with rsync in a single string. Although Ansible allows an array this can cause problems if we try to add multiple --include args as it was reported in https://github.com/ansistrano/deploy/commit/e98942dc969d4e620313f00f003a7ea2eab67e86
ansistrano_rsync_set_remote_user: yes # See [ansible synchronize module](http://docs.ansible.com/ansible/synchronize_module.html). Options are yes, no.

# Hooks: custom tasks if you need them
ansistrano_before_symlink_tasks_file: "{{ playbook_dir }}/roles/useradmin/tasks/ansistrano/before_symlink.yml"
ansistrano_after_symlink_tasks_file: "{{ playbook_dir }}/roles/useradmin/tasks/ansistrano/after_symlink.yml"
