---
env: development
virtual_host: 192.168.111.171

postgres:
  version: "9.4"
  database:
    host: 127.0.0.1/32
    name: useradmin_development
    user: useradmin
    password: useradmin
    user_roles: "LOGIN,CREATEDB"

admins:
  - bforma
  - svdiepen

passenger:
  max_pool_size: 10
  max_instances_per_app: 5
  friendly_error_pages: "on"

surfconext:
  idp:
    sso_url: http://192.168.111.171:8080/idp/SingleSignOnService

ruby_user: surfsara
ruby_user_group: surfsara
ruby_user_home: "/home/{{ ruby_user }}"
rbenv_root: "{{ ruby_user_home }}/.rbenv"
rbenv_repo: "git://github.com/sstephenson/rbenv.git"
rbenv_version: v1.0.0

rbenv_plugins:
  - { name: "ruby-build",         repo: "git://github.com/sstephenson/ruby-build.git",         version: "HEAD" }
